In [15]:
import pandas as pd
emp_edu_data = pd.read_csv('emp-edu.csv')
medical_data = pd.read_csv('medical.csv')

In [16]:
new_emp_edu_data = emp_edu_data[['ssn', 'gender', 'birth_date', 'education', 'occupation', 'salary', 'years_of_experience', 'employment_timestamp']]
new_medical_data = medical_data[['ssn', 'height', 'weight', 'blood_pressure', 'cholesterol_level', 'consultation_timestamp']]

In [17]:
new_emp_edu_data = new_emp_edu_data.drop_duplicates()
new_emp_edu_data = new_emp_edu_data[new_emp_edu_data.birth_date.str.split('/', expand=True)[1].astype(int) < 13]
new_emp_edu_data = new_emp_edu_data.dropna()
# ssn = new_emp_edu_data['ssn']
# new_emp_edu_data[ssn.isin(ssn[ssn.duplicated()])].sort_values('ssn')
# new_emp_edu_data['ssn'].value_counts()
len(new_emp_edu_data)

44518

In [19]:
new_medical_data = new_medical_data.drop_duplicates()
new_medical_data = new_medical_data.dropna()
new_medical_data = new_medical_data[new_medical_data.height > 0]
new_medical_data = new_medical_data[new_medical_data.weight > 0]
ssn = new_medical_data['ssn']
new_medical_data[ssn.isin(ssn[ssn.duplicated()])].sort_values('ssn')
# print(len(new_medical_data))
# len(set(medical_data.ssn))

,ssn,height,weight,blood_pressure,cholesterol_level,deceased_status,consultation_timestamp
12837,a103328255,173,128,76,227,0,2017-12-08t14:52+00:00
23886,a103328255,173,128,76,227,1,2017-12-08t14:52+00:00
38655,a106288422,178,98,74,121,0,2016-04-22t20:05+00:00
42149,a106288422,178,98,74,121,1,2016-04-22t20:05+00:00
18186,a107653795,158,53,75,130,1,2017-06-17t17:03+00:00
13124,a107653795,158,53,75,130,0,2017-06-17t17:03+00:00
29781,a145412862,186,100,71,77,0,2017-04-25t13:43+00:00
21854,a145412862,186,100,71,77,1,2017-04-25t13:43+00:00
42472,a195055723,187,55,75,208,1,2016-07-22t23:43+00:00
34780,a195055723,187,55,75,208,0,2016-07-22t23:43+00:00
28775,a197736709,182,104,75,237,0,2014-11-25t03:14+00:00
35297,a197736709,182,104,75,237,1,2014-11-25t03:14+00:00
10450,b105394363,172,45,76,52,0,2017-03-18t24:03+00:00
28236,b105394363,172,45,76,52,1,2017-03-18t24:03+00:00
2962,b112146106,186,140,77,188,0,2017-04-08t19:22+00:00
30968,b112146106,186,140,77,188,1,2017-04-08t19:22+00:00
42267,b118487431,174,112,78,116,1,2015-01-09t15:55+00:00
29407,b118487431,174,112,78,116,0,2015-01-09t15:55+00:00
25731,b134558402,170,130,74,137,0,2017-12-12t19:18+00:00
40725,b134558402,170,130,74,137,1,2017-12-12t19:18+00:00
29822,b136044850,175,127,77,66,1,2017-08-20t21:41+00:00
42287,b136044850,175,127,77,66,0,2017-08-20t21:41+00:00
18394,b142612504,166,75,79,225,0,2017-01-17t08:57+00:00
28225,b142612504,166,75,79,225,1,2017-01-17t08:57+00:00
25101,b164683239,168,107,76,107,1,2016-12-10t17:10+00:00
29558,b164683239,168,107,76,107,0,2016-12-10t17:10+00:00
28272,b169033659,178,67,78,86,1,2018-04-24t22:41+00:00
14700,b169033659,178,67,78,86,0,2018-04-24t22:41+00:00
2827,b171423713,165,61,80,148,1,2018-05-01t24:29+00:00
38136,b171423713,165,61,80,148,0,2018-05-01t24:29+00:00
...,...,...,...,...,...,...,...
29062,f192360972,179,84,76,204,0,2018-03-06t20:19+00:00
43245,f192360972,179,84,76,204,1,2018-03-06t20:19+00:00
11369,g121148851,177,87,67,198,1,2016-02-02t10:27+00:00
4511,g121148851,177,87,67,198,0,2016-02-02t10:27+00:00
36976,g121251884,183,57,72,207,0,2016-03-19t18:23+00:00
12532,g121251884,183,57,72,207,1,2016-03-19t18:23+00:00
6165,g131214178,155,143,72,161,1,2015-07-23t22:57+00:00
28429,g131214178,155,143,72,161,0,2015-07-23t22:57+00:00
15123,g160918903,151,107,71,163,0,2018-05-09t09:21+00:00
15556,g160918903,151,107,71,163,1,2018-05-09t09:21+00:00
36795,g174713409,162,107,76,139,0,2016-02-09t18:16+00:00
13402,g174713409,162,107,76,139,1,2016-02-09t18:16+00:00
22205,g197803589,159,47,75,178,0,2016-04-21t10:33+00:00
13803,g197803589,159,47,75,178,1,2016-04-21t10:33+00:00
41500,h155140837,153,52,73,124,1,2018-05-25t24:22+00:00
16653,h155140837,153,52,73,124,0,2018-05-25t24:22+00:00
39128,h187276808,183,78,72,131,0,2016-10-27t02:14+00:00
40040,h187276808,183,78,72,131,1,2016-10-27t02:14+00:00
16268,h197682724,152,126,77,230,1,2017-07-17t03:24+00:00
36332,h197682724,152,126,77,230,0,2017-07-17t03:24+00:00
16785,i108994274,161,127,72,191,0,2018-02-15t11:12+00:00
44832,i108994274,161,127,72,191,1,2018-02-15t11:12+00:00
33962,i155085094,171,128,79,232,1,2017-07-10t13:23+00:00
785,i155085094,171,128,79,232,0,2017-07-10t13:23+00:00
14147,i155675085,174,48,79,128,1,2015-03-05t01:33+00:00
42933,i155675085,174,48,79,128,0,2015-03-05t01:33+00:00
27317,i181460290,186,103,79,148,1,2015-06-25t10:27+00:00
34971,i181460290,186,103,79,148,0,2015-06-25t10:27+00:00
4032,i196050071,169,96,77,169,0,2018-02-06t19:20+00:00
31671,i196050071,169,96,77,169,1,2018-02-06t19:20+00:00

In [8]:
ssn_id = set(new_emp_edu_data['ssn']) & set(new_medical_data['ssn'])
new_emp_edu_data = new_emp_edu_data[new_emp_edu_data.ssn.isin(ssn_id)]
res = pd.merge(new_emp_edu_data, new_medical_data, on='ssn')
# res.isnull().values.any()
res = res[abs(res.employment_timestamp.str.split('-', expand=True)[0].astype(int) - res.consultation_timestamp.str.split('-', expand=True)[0].astype(int)) < 5]

In [13]:
res.to_csv('result.csv')